mongodb-js/mongodb-schema

- lib/field-collection.js
- test/field-order.test.js
Example: 
1. _id
2. AAA
3. bbb
4. CcC
5. cDE
> INT-156 field sort order: _id on top, case-insensitive.

- lib/field-collection.js
- lib/field.js
- lib/type-collection.js
- lib/types/type.js
- test/basic-embedded-document-array.test.js
- test/basic-embedded-documents.test.js
- test/nested-document-path.test.js
```
{
name: "Thomas",
address: {
street: "Park St",
no: 16,
postcode: 12345,
city: "Sydney"
},
current_mood: "enthusiastic"
}
```
`Field#name` only contains the local name, e.g. `street` in above example. It is useful to also be able to access the full path in dot-notation, e.g. `address.street`. 
This change adds `Field#path` and is automatically set on document parsing.
Also added tests to verify.
> added Field#path as full dot-notation path

- lib/field.js
- lib/parse-native.js
- lib/types/constant.js
- lib/types/primitive.js
- lib/types/type.js
- test/basic-unique.test.js
- store 10,000 numeric values, but only 100 strings
- add `has_duplicates` on a type level, propagate up to field level
- added tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb-js/mongodb-schema/30)
> INT-1243 minicharts 1000

- bin/mongodb-schema.js
I found that with the `process.exit(0)` call, the pipe to stdout gets destroyed prematurely before the next process in the pipe has all the data. 
For example: 
```
mongodb-schema localhost:27017 test.foo | morelikethis | mgeneratejs -n 100
```
The script `morelikethis` would not get the full schema output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb-js/mongodb-schema/33)
> avoid premature exit when piping to stdout

- lib/parse-native.js
- test/basic.test.js
a lodash collection simply duck-type checks for the presence of a field `.length`.
Note: This doesn't actually fix the bug, these changes are just a precaution.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb-js/mongodb-schema/34)
> INT-1487 don’t use _.each to iterate over objects + test

- bin/mongodb-schema
- package.json
- switch between find() and sample() with the `--sample` / `--no-sample` flag
- disable promoting values to Javascript types with the `--no-promote` flag
This also renames the `--sample` to `--number` parameter for consistency, so is a backwards breaking change.
> COMPASS-286 add --no-sample and --no-promote options to executable.

- README.md
- bin/mongodb-schema
- lib/index.js
- lib/semantic-types/email.js
- lib/semantic-types/geojson.js
- lib/semantic-types/index.js
- lib/stream.js
- package.json
- test/options.test.js
- test/semantic-types.test.js
Semantic types enable users to provide domain knowledge of their stored data. While MongoDB's flexible schema model enables storing any type of data, there is ...
See README for additional explanation of the features.
> Added semantic type detection feature and ability to disable value storage

- lib/stream.js
- test/basic.test.js
Allowing to have array like field names in schema
> COMPASS-1797 Fields 'foo' and 'foo[]' can cause 'foo[]' to disappear

- examples/parse-from-file.js
With newer versions of node you need to specifically provide a path (i think older versions of node let you just give a string) when creating a read stream. example file doesn't work without supplying a proper path.
> fix example read from file

- lib/stream.js
In the latest version of `bson` library, `_bsontype` property is added to value's prototype, but `_.has` only looks for in object's own properties. This means incorrect type might be returned. This PR fixes the issue by access the `_bsontype` directly.
> access _bsontype directly instead of _.has

- README.md
- examples/parse-schema.js
The README and the parse-schema.js example were outdated, this just updates them.
> chore: Update parseSchema and semanticTypes examples

- .travis.yml
- package-lock.json
- package.json
You could always discuss if a major version bump is actually needed, since the API of mongodb-schema actually seems to work fine running both version 12/14 --> but I have only tested using `.nvm` on Mac OS.
I looked at the previous commit history, and noticed the use of a beta flag on last major semver upgrade, so included such a flag here as well.
> End support for legacy Node.js versions 🩺

- .eslintrc
- lib/index.js
- package.json
- test/promise-or-callback.test.js
Based on this excellent SO answer:
https://stackoverflow.com/a/36838115/3694288
The objective is to make the library more available and easy to use.
I was thinking about adding documentation in the README.md, bug I think most people would simply expect the promise nature of libraries these days. Maybe in the future we can have a talk about typescript support, giving end-users a better idea about the API of the library.
> Added promise support for library

- .depcheckrc
- package-lock.json
- package.json
- src/index.ts
- src/schema-analyzer.ts
- src/semantic-types/email.ts
- src/stream.ts
- test/all-bson-types.test.ts
- test/time-testing.ts
Most main changes are in [src/schema-analyzer.ts](https://github.com/mongodb-js/mongodb-schema/compare/COMPASS-6720-update-schema-types?expand=1#diff-014a95a710306ef85390ea1408c13c1a7434e25c418fc4ad94a372d9f00df729) which it looks like GitHub is minimizing by default.
We now export the various types so places like compass-schema and import-export can use them. In a follow up pr we'll move the [`gather-fields`](https://github.com/mongodb-js/compass/blob/main/packages/compass-import-export/src/export/gather-fields.ts) function from `compass-import-export` here so other places can use it (like in the wizard in compass-aggregations). https://github.com/mongodb-js/compass/blob/main/packages/compass-import-export/src/export/gather-fields.ts
These changes are a speedup, mostly from not repeating …
> feat: export schema types, remove lodash dependency, speed up analysis COMPASS-6720

- .github/workflows/unit-tests.yml
So we can use `stream/promises` in https://github.com/mongodb-js/mongodb-schema/pull/192
> chore(testing): remove node 14, add node 20 for github workflow tests

- src/index.ts
- src/schema-analyzer.ts
- src/stream.ts
- test/get-schema-paths.test.ts
This is something we already have in Compass that we're moving here. Here's where it was in Compass (after merging and releasing this pr we'll remove it in Compass and start using it from this package): https://github.com/mongodb-js/compass/blob/892e83129ea3a33ba42c1fc1f5f094b45fd17885/packages/compass-import-export/src/export/gather-fields.ts#L36
This should also speed up how we do it in Compass as we don't need to finalize the schema to get the schema paths. The overload on the options in the `stream` file is a big gross, open to suggestions on how to make this a bit cleaner.
> feat: add getSchemaPaths helper

- src/schema-analyzer.ts
- test/get-schema-paths.test.ts
Compass assumes these are sorted, I'm thinking it's easier to have this here than in any consumers of this package/function, but if folks feel differently we can not merge this. No strong preference.
Will make this a minor.
> feat: sort paths from getSchemaPaths

- README.md
- src/index.ts
- src/schema-analyzer.ts
- src/stream.ts
- test/all-bson-types-fixture.ts
- test/all-bson-types.test.ts
- test/simplified-schema.test.ts
COMPASS-6979
Another option instead of adding a separate helper would be to add a lot of logic around an optional in the existing schema parser. This would have added a lot of branching logic, and likely would have made this helper a bit slower. 
This will be used in Compass for generating a schema to pass to the large language model / ai.
> feat: add getSimplifiedSchema helper which returns a schema without any metadata COMPASS-6979

- bin/mongodb-schema
- package-lock.json
- package.json
- src/index.ts
The sample option wasn't working because mongodb-collection-sample's returned stream wasn't iterating. I switched it to using a sample aggregation and now that dep can be gone from our dependencies here and in compass.
The repeat argument wasn't doing anything.
This is much simpler with just async iterators over the cursor we get when either doing a find or a sample aggregation.
The schemaStats functions weren't working because the export is now the `default` object.
We weren't using the new analyzer methods.
> chore: Fix bin/mongodb-schema script

- src/schema-analyzer.ts
- test/basic.test.ts
- test/mixed-type-nested.test.ts
Fixes: https://github.com/mongodb-js/mongodb-schema/issues/211
> fix: use prototypeless objects for field-to-type mappings

- package-lock.json
- package.json
- src/schema-accessor.ts
- src/schema-convertors/internalToMongoDB.ts
- src/schema-convertors/internalToStandard.test.ts
- src/schema-convertors/internalToStandard.ts
- src/schema-convertors/util.ts
- test/integration/generateAndValidate.ts
Very similar to [$jsonSchema](https://github.com/mongodb-js/mongodb-schema/pull/218). The difference is that instead of mapping the internal types to bsonType, we map it to JSON Schema.
This is done so that it fits the [Relaxed Extended JSON definition](https://github.com/mongodb/specifications/blob/master/source/extended-json/extended-json.md) - it will be either
- one of the basic [JSON Schema types](https://json-schema.org/draft/2020-12/json-schema-validation#name-type)
- refer to a definition describing the relaxed extended JSON
The definition are mostly taken from @mcasimir's [POC](https://github.com/mongodb-js/compass/pull/5690/files), I checked them with specs and made several updates:
- binary subtype pattern changed from `^[0-9a-fA-F]{2}$'` to `^[0-9a-fA-F]{1,2}$' (it says "BSON …
> feat: internal to Standard JSON Schema conversion COMPASS-8700

- src/schema-convertors/internalToExpanded.test.ts
- src/schema-convertors/internalToExpanded.ts
- src/types.ts
- test/integration/generateAndValidate.ts
In the last piece of the puzzle, we're generating expanded JSON Schema. 
Differences from the JSON Schema:
- it includes `x-bsonType` along the `type` (using the same map as we have for `$jsonSchema`)
- it includes `x-metaData` and `x-sampleValues` (these are taken from the internal schema)
- because of these additional properties, we don't do the array notation for mixed types (so the logic for 'plainTypes' is gone)
Notes: metadata (count, probability, hasDuplicates) are present both on the type and field level in the internal schema. I kept this. Sample values are present on the type level and are not present in objects/arrays in the internal schema, so again we're just taking them when they're available.
> feat: internal to Expanded JSON Schema conversion COMPASS-8702 

- src/schema-analyzer.ts
- test/bloated.test.ts
We already had a cap for strings. This PR adds cap for Binary and Code
> fix: crop bloated code and binary COMPASS-8902

- .github/workflows/unit-tests.yml
- package.json
Otherwise, `npm install && npm test` (aka `npm it`) fails on a clean checkout, and using this package as a git dependency wouldn't work.
> chore: rename `prepack` to `prepare` in package.json

- src/index.ts
- src/schema-analyzer.ts
- test/bloated.test.ts
Optional - keeping the existing 10k as default.
> feat: configurable limit for sample values COMPASS-8984

- src/schema-analyzer.ts
- test/bloated.test.ts
Again an optional parameter. I had hard time coming up with the name, let me know if you have better suggestion. This one is a hard limit that can be imposed on the complexity (represented by unique field count). Together with the lower stored samples limit, it can be used as a prevention mechanism for running out of memory during the analysis itself (https://jira.mongodb.org/browse/COMPASS-8526), or later down the line (such as the new schema export conversion or file download).
> feat: optional field count threshold

- src/schema-converters/internalToMongoDB.test.ts
- src/schema-converters/internalToMongoDB.ts
- test/all-bson-types-fixture.ts
- test/integration/generateAndValidate.test.ts
COMPASS-9110
Adds an integration test that creates a validation rule with all types and some edge cases (nested empty arrays/objects).
Opening as a draft, I need to fix the error on the test.
> fix: update MongoDB schema converter to remove invalid fields, add integration test

- package.json
- src/index.ts
- src/to-typescript.spec.ts
- src/to-typescript.ts
Extracted from https://github.com/mongodb-js/devtools-shared/pull/520, will be used there.
> feat: convert a MongoDBJSONSchema to a TypeScript type snippet MONGOSH-2058

- src/index.ts
- src/to-typescript.ts
- src/types.ts
Forgot to include this in https://github.com/mongodb-js/mongodb-schema/pull/237
> chore: export the JSONSchema type
